/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_util_NativeUtil */

#ifndef _Included_com_util_NativeUtil
#define _Included_com_util_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_util_NativeUtil
 * Method:    getStringC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_NativeUtil_getStringC
  (JNIEnv *, jclass);

/*
 * Class:     com_util_NativeUtil
 * Method:    myEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_NativeUtil_myEncrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_util_NativeUtil
 * Method:    myDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_NativeUtil_myDecrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
